name: Deply to Dev

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Copy code
      run: cp -r -f . /home/cloud/app/ex-json-api
    - name: Install deps
      working-directory: /home/cloud/app/ex-json-api
      run: yarn
    - name: Restart service
      working-directory: /home/cloud/app/ex-json-api
      run: pm2 start

    